stages:
  - test

variables:
  BUN_VERSION: "latest"

test:
  stage: test
  image: oven/bun:${BUN_VERSION}
  before_script:
    - bun --version
  script:
    - bun install
    - bun test
  only:
    - main
    - merge_requests

